### ISSUE TITLE
Unobfuscate source code

### ISSUE THREAD

**Issue by uheplm** [mygnet/anemona-secrets#1]
The password manager is very sensitive code that **should be completely open and easy to read.** Otherwise, there are doubts about the safety of the extension, since it is difficult to check its safety. Please post the uncompressed source code so that you can be sure that your extension is safe.

**Comment by mygnet** [comment]
> The password manager is very sensitive code that **should be completely open and easy to read.** Otherwise, there are doubts about the safety of the extension, since it is difficult to check its safety. Please post the uncompressed source code so that you can be sure that your extension is safe.

Hello, you are absolutely right, I release the source code so that you can analyze it, look for any vulnerability, suggestions or collaboration. Greetings.

**Comment by shaik9944** [comment]
Snap chat password

**Comment by shaik9944** [comment]
Snapchat email verification
